package org.sakshi.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Every colour the app uses, as plain 0xRRGGBB integers so the contrast test can read them without Compose.
 *
 * [outlineVariant] is decorative only (card edges, dividers). Anything that identifies a control or a block
 * (input borders, button outlines, epistemic rules) uses [outlineStrong], which meets 3:1 against every surface.
 */
internal class Palette(
    val background: Int,
    val surface: Int,
    val surfaceQuiet: Int,
    val ink: Int,
    val muted: Int,
    val outlineVariant: Int,
    val outlineStrong: Int,
    val gold: Int,
    val green: Int,
    val red: Int,
    val primary: Int,
    val onPrimary: Int,
    val primaryContainer: Int,
    val onPrimaryContainer: Int,
    val onGold: Int,
    val goldContainer: Int,
    val onGoldContainer: Int,
    val onGreen: Int,
    val greenContainer: Int,
    val onGreenContainer: Int,
    val onRed: Int,
    val redContainer: Int,
    val onRedContainer: Int,
    val inverseSurface: Int,
    val inverseOnSurface: Int,
)

internal val LightPalette = Palette(
    background = 0xFAF7F0,
    surface = 0xFFFDF8,
    surfaceQuiet = 0xF1ECE0,
    ink = 0x25212A,
    muted = 0x655C6E,
    outlineVariant = 0xCEC6B9,
    outlineStrong = 0x857C8F,
    gold = 0x78551B,
    green = 0x27644E,
    red = 0x983F39,
    primary = 0x3D3346,
    onPrimary = 0xFFFDF8,
    primaryContainer = 0xE8E1EB,
    onPrimaryContainer = 0x25212A,
    onGold = 0xFFFDF8,
    goldContainer = 0xF0E4C8,
    onGoldContainer = 0x3B2A09,
    onGreen = 0xFFFDF8,
    greenContainer = 0xDCEDE3,
    onGreenContainer = 0x11372A,
    onRed = 0xFFFDF8,
    redContainer = 0xF5DFDC,
    onRedContainer = 0x5C1C17,
    inverseSurface = 0x25212A,
    inverseOnSurface = 0xFAF7F0,
)

internal val DarkPalette = Palette(
    background = 0x17151A,
    surface = 0x242129,
    surfaceQuiet = 0x2E2A35,
    ink = 0xEEE8DC,
    muted = 0xC2BACA,
    outlineVariant = 0x45404A,
    outlineStrong = 0x8F8798,
    gold = 0xDBBB79,
    green = 0xA2D0BB,
    red = 0xE1AAA5,
    primary = 0xD8CEE0,
    onPrimary = 0x17151A,
    primaryContainer = 0x3D3446,
    onPrimaryContainer = 0xEEE8DC,
    onGold = 0x17151A,
    goldContainer = 0x4A3B1C,
    onGoldContainer = 0xF3E4BF,
    onGreen = 0x17151A,
    greenContainer = 0x24493A,
    onGreenContainer = 0xD4ECDF,
    onRed = 0x17151A,
    redContainer = 0x5A2824,
    onRedContainer = 0xF6D3CF,
    inverseSurface = 0xEEE8DC,
    inverseOnSurface = 0x17151A,
)

private const val OPAQUE = 0xFF000000.toInt()

/** An opaque Compose colour from a 0xRRGGBB integer. */
internal fun rgb(value: Int): Color = Color(OPAQUE or value)

/** Maps the palette onto Material 3 roles. Gold is secondary, green tertiary, red error. */
internal fun Palette.lightScheme(): ColorScheme = lightColorScheme(
    primary = rgb(primary),
    onPrimary = rgb(onPrimary),
    primaryContainer = rgb(primaryContainer),
    onPrimaryContainer = rgb(onPrimaryContainer),
    inversePrimary = rgb(primaryContainer),
    secondary = rgb(gold),
    onSecondary = rgb(onGold),
    secondaryContainer = rgb(goldContainer),
    onSecondaryContainer = rgb(onGoldContainer),
    tertiary = rgb(green),
    onTertiary = rgb(onGreen),
    tertiaryContainer = rgb(greenContainer),
    onTertiaryContainer = rgb(onGreenContainer),
    background = rgb(background),
    onBackground = rgb(ink),
    surface = rgb(surface),
    onSurface = rgb(ink),
    surfaceVariant = rgb(surfaceQuiet),
    onSurfaceVariant = rgb(muted),
    surfaceTint = rgb(primary),
    inverseSurface = rgb(inverseSurface),
    inverseOnSurface = rgb(inverseOnSurface),
    error = rgb(red),
    onError = rgb(onRed),
    errorContainer = rgb(redContainer),
    onErrorContainer = rgb(onRedContainer),
    outline = rgb(outlineStrong),
    outlineVariant = rgb(outlineVariant),
    scrim = Color.Black,
    surfaceBright = rgb(surface),
    surfaceDim = rgb(surfaceQuiet),
    surfaceContainerLowest = rgb(surface),
    surfaceContainerLow = rgb(surface),
    surfaceContainer = rgb(surface),
    surfaceContainerHigh = rgb(surfaceQuiet),
    surfaceContainerHighest = rgb(surfaceQuiet),
)

/** Same mapping as [lightScheme], built with the dark baseline. */
internal fun Palette.darkScheme(): ColorScheme = darkColorScheme(
    primary = rgb(primary),
    onPrimary = rgb(onPrimary),
    primaryContainer = rgb(primaryContainer),
    onPrimaryContainer = rgb(onPrimaryContainer),
    inversePrimary = rgb(onPrimary),
    secondary = rgb(gold),
    onSecondary = rgb(onGold),
    secondaryContainer = rgb(goldContainer),
    onSecondaryContainer = rgb(onGoldContainer),
    tertiary = rgb(green),
    onTertiary = rgb(onGreen),
    tertiaryContainer = rgb(greenContainer),
    onTertiaryContainer = rgb(onGreenContainer),
    background = rgb(background),
    onBackground = rgb(ink),
    surface = rgb(surface),
    onSurface = rgb(ink),
    surfaceVariant = rgb(surfaceQuiet),
    onSurfaceVariant = rgb(muted),
    surfaceTint = rgb(primary),
    inverseSurface = rgb(inverseSurface),
    inverseOnSurface = rgb(inverseOnSurface),
    error = rgb(red),
    onError = rgb(onRed),
    errorContainer = rgb(redContainer),
    onErrorContainer = rgb(onRedContainer),
    outline = rgb(outlineStrong),
    outlineVariant = rgb(outlineVariant),
    scrim = Color.Black,
    surfaceBright = rgb(surface),
    surfaceDim = rgb(surfaceQuiet),
    surfaceContainerLowest = rgb(surface),
    surfaceContainerLow = rgb(surface),
    surfaceContainer = rgb(surface),
    surfaceContainerHigh = rgb(surfaceQuiet),
    surfaceContainerHighest = rgb(surfaceQuiet),
)
